services:
  backend:
    image: ml-classification-backend
    build:
      context: ./
      dockerfile: Dockerfile

  frontend:
    image: nginx:latest
    volumes:
      - ./ml-classification/build:/var/www/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"


